import { GoogleGenAI } from "@google/genai";
import { ImageFile } from "../types";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export const generateFix = async (
  originalImage: ImageFile,
  fixDescription: string
): Promise<string> => {
  try {
    // We use the default image editing model
    const model = 'gemini-2.5-flash-image';
    
    // Construct a specific prompt for "fixing" or "cleaning" while maintaining realism
    const prompt = `
      You are an expert visualization AI specialized in construction repairs, interior design, and housekeeping.
      I will provide an image and a description of a desired improvement (fix, renovation, or cleanup).

      User Request: "${fixDescription}"

      Task:
      1. Analyze the input image and the user's request.
      2. Generate a new version of the image with the request applied.
      3. If the request involves cleaning, housekeeping, or organizing:
         - Remove debris, dust, trash, and clutter.
         - Organize scattered items (tools, furniture, boxes) neatly.
         - Make surfaces look swept, mopped, and wiped down.
         - Ensure the space looks clean and "house kept".
      4. If the request involves construction repairs:
         - Fix the specified defects (cracks, holes, broken items) indistinguishably from the original structure.
      5. CRITICAL: Maintain the exact same perspective, camera angle, lighting conditions, and surrounding environment details (textures, shadows, colors, background).
      6. The result must be a photorealistic exact detailed replica of the original scene, only modified where requested.

      Do not add any text, labels, or overlays. Return only the image.
    `;

    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            inlineData: {
              data: originalImage.data,
              mimeType: originalImage.mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
    });

    // Extract the generated image
    let generatedImageBase64: string | null = null;

    if (response.candidates && response.candidates[0].content && response.candidates[0].content.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
          generatedImageBase64 = part.inlineData.data;
          break;
        }
      }
    }

    if (!generatedImageBase64) {
      throw new Error("No image generated by the model.");
    }

    return `data:image/png;base64,${generatedImageBase64}`;

  } catch (error) {
    console.error("Error generating fix:", error);
    throw error;
  }
};